Repository gazebosim/gz-common, pull requests merged in 2020-09, with the labels that each got.

#92 Small Remotery tutorials fixes
  profiler/src/RemoteryProfilerImpl.cc
  tutorials/profiler.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#93 Fix trajectory info memory leak
  graphics/src/Animation.cc
Labels: beta, bug, 🏰 citadel, 📜 blueprint, 🔮 dome

#94 Remove invalid URI warning
  src/URI.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#95 ⬆️ 3.6.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#90 Deprecated common:Time
  .github/ci-bionic/after_make.sh
  CMakeLists.txt
  include/ignition/common/Time.hh
  include/ignition/common/Timer.hh
  include/ignition/common/WorkerPool.hh
  src/CMakeLists.txt
  src/Time.cc
  src/Time_TEST.cc
  src/Timer.cc
  src/WorkerPool.cc
  src/WorkerPool_TEST.cc
Labels: enhancement

#97 Fix env behavior to return true on empty vars
  include/ignition/common/Util.hh
  src/Util.cc
  src/Util_TEST.cc
  tools/code_check.sh
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#98 Fix more Animation memory leak
  graphics/include/ignition/common/Animation.hh
  graphics/src/Animation.cc
  graphics/src/SkeletonAnimation.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome
