Repository gazebosim/gz-common, pull requests merged in 2020-11, with the labels that each got.

#119 ci: remove two known flaky tests
  CMakeLists.txt
  src/CMakeLists.txt
  src/WorkerPool_TEST.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#116 Do not hardcode USE_EXTERNAL_TINYXML2 to OFF on Windows
  CMakeLists.txt
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#105 Fix video encoder timing
  av/include/ignition/common/Video.hh
  av/src/Video.cc
  av/src/VideoEncoder.cc
  test/integration/CMakeLists.txt
  test/integration/encoder_timing.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#100 Add transformation matrix to ColladaExport
  graphics/include/ignition/common/ColladaExporter.hh
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaExporter_TEST.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#127 Fix IGN_HOMEDIR on Windows
  Migration.md
  include/ignition/common/Util.hh
Labels: Windows, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
