Repository gazebosim/gz-common, pull requests merged in 2020-10, with the labels that each got.

#101 Fix loading dae file with hierarchical node that does not have a name
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  test/data/box_with_hierarchical_nodes.dae
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#102 [ign-common3] Support fuel URLs for textures
  graphics/src/Material.cc
  graphics/src/Material_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#106 Add Console example
  examples/CMakeLists.txt
  examples/README.md
  examples/console.cc
Labels: documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#103 [ign-common3] Improve fork experience
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#107 [ign-common3] Miscellaneous Cleanups
  examples/CMakeLists.txt
  include/ignition/common/StringUtils.hh
  src/Filesystem_TEST.cc
  src/StringUtils.cc
  src/StringUtils_TEST.cc
  src/SystemPaths_TEST.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#108 ⬆️ 3.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#111 Call ignition::common::load() from Video constructor
  av/src/Video.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#113 Cleanup: Drop unused forward declaration
  graphics/include/ignition/common/Animation.hh
  graphics/src/Animation.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
