Repository gazebosim/gz-common, pull requests merged in 2021-09, with the labels that each got.

#246 3 ➡️ 4
  av/src/VideoEncoder_TEST.cc
  bitbucket-pipelines.yml
  events/include/ignition/common/Event.hh
  events/src/Event_TEST.cc
Labels: beta, 🏢 edifice, 🏯 fortress

#244 Add functions and objects for Temporary Directories
  include/ignition/common/TempDirectory.hh
  src/CMakeLists.txt
  src/Console.cc
  src/Console_TEST.cc
  src/SystemPaths_TEST.cc
  src/TempDirectory.cc
  src/TempDirectory_TEST.cc
  test/test_config.h.in
Labels: beta, 🏢 edifice, 🏯 fortress

#248 Remove ign-utils from TempDirectory
  include/ignition/common/TempDirectory.hh
  src/CMakeLists.txt
  src/TempDirectory.cc
Labels: bug, beta, 🏢 edifice, 🏯 fortress

#251 🎈 4.3.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice, 🏯 fortress

#252 README: link directly to Contributing page
  README.md
Labels: 🏢 edifice, 🏯 fortress

#250 Use direct evaluation for SKIP_av.
  test/integration/CMakeLists.txt
Labels: 🏢 edifice, 🏯 fortress

#253 Add macos install instructions
  tutorials/install.md
Labels: documentation, macOS, 🏢 edifice, 🏯 fortress

#254 🎈 4.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏯 fortress
