Repository gazebosim/gz-common, pull requests merged in 2021-01, with the labels that each got.

#150 ⬆️ 3.10.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#152 Collada transparency is opposite.
  graphics/include/ignition/common/Material.hh
  graphics/src/ColladaExporter.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#146 Add Windows installation; move installation in README to tutorial
  README.md
  tutorials.md.in
  tutorials/install.md
  tutorials/profiler.md
Labels: Windows, documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#153 Prepare for 3.10.1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#155 Added capsule mesh
  graphics/include/ignition/common/MeshManager.hh
  graphics/src/MeshManager.cc
  graphics/src/SubMesh_TEST.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#154 Added ellipsoid mesh
  graphics/include/ignition/common/MeshManager.hh
  graphics/src/MeshManager.cc
  graphics/src/SubMesh_TEST.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#149 Disable failing VideoEncoder and Audioecoder tests on Windows
  av/src/AudioDecoder_TEST.cc
  av/src/CMakeLists.txt
  av/src/VideoEncoder.cc
  av/src/VideoEncoder_TEST.cc
  graphics/src/CMakeLists.txt
  src/Filesystem_TEST.cc
Labels: AV, Windows, tests, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
