Repository gazebosim/gz-common, pull requests merged in 2021-04, with the labels that each got.

#192 Use matching malloc/free for AudioDecoder.
  av/src/AudioDecoder.cc
  av/src/AudioDecoder_TEST.cc
Labels: bug, 🏰 citadel, 📜 blueprint, 🔮 dome

#194 Fixed tutorial link
  README.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#139 Function to serialize compressed image to buffer
  graphics/include/ignition/common/Image.hh
  graphics/src/Image.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#195 Prepare for 3.12.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#197 Improved Windows support
  include/ignition/common/Util.hh
  src/Filesystem.cc
  src/SystemPaths.cc
  src/URI.cc
Labels: Windows, 🏰 citadel, 📜 blueprint, 🔮 dome

#200 Fixed colladaLoader on Windows
  graphics/src/ColladaLoader.cc
Labels: Windows, bug, 🏰 citadel, 📜 blueprint, 🔮 dome

#201 Avoid duplication of / in joinPaths (Windows)
  include/ignition/common/Filesystem.hh
  src/Filesystem.cc
  src/Filesystem_TEST.cc
Labels: Windows, bug, 🏰 citadel, 📜 blueprint, 🔮 dome

#204 Remove ColladaExporter path constraint
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaExporter_TEST.cc
Labels: 🏢 edifice, 🏯 fortress

#205 Add function to convert single channel image data to RGB image
  graphics/include/ignition/common/Image.hh
  graphics/src/Image_TEST.cc
Labels: 🏰 citadel, 🔮 dome

#207 Prepare for 3.13.0 release
  BUILD.bazel
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome

#199 Backport #188: Fix crash when using BVH animations
  graphics/include/ignition/common/SkeletonAnimation.hh
  graphics/src/Skeleton.cc
  graphics/src/SkeletonAnimation.cc
Labels: bug, 🏰 citadel, 🔮 dome
