Repository gazebosim/gz-common, pull requests merged in 2021-03, with the labels that each got.

#162 Fix saving image to PNG (swap red and blue)
  graphics/src/Image.cc
  graphics/src/Image_TEST.cc
  test/data/red_blue_colors.png
Labels: bug, 🏰 citadel, 📜 blueprint, 🔮 dome

#176 3 ➡️ 4
  av/include/ignition/common/CMakeLists.txt
  av/include/ignition/common/HWEncoder.hh
  av/include/ignition/common/HWVideo.hh
  av/include/ignition/common/Video.hh
  av/include/ignition/common/VideoEncoder.hh
  av/include/ignition/common/ffmpeg_inc.hh
  av/src/CMakeLists.txt
  av/src/HWEncoder.cc
  av/src/Util.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
  av/src/VideoEncoder_TEST.cc
  av/src/ffmpeg_inc.cc
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Image.cc
  graphics/src/Image_TEST.cc
  test/data/rectangle.dae
  test/data/red_blue_colors.png
  test/data/test_video.mp4
  test/integration/CMakeLists.txt
  test/integration/video_encoder.cc
  tutorials.md.in
  tutorials/hw-encoding.md
  tutorials/profiler.md
Labels: 🏢 edifice

#178 🎈 3.11.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#183 Relax expectation so encoder test passes on ARM
  test/integration/video_encoder.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#182 Revert "Associate library materials effect with meshes (#151)"
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  test/data/rectangle.dae
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#184 🎈 3.11.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#179 Master branch updates
  .github/workflows/ci.yml
  README.md
  tutorials/profiler.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#160 Cleanup and add Implementation pointer to Animation classes
  .github/ci/packages.apt
  CMakeLists.txt
  graphics/include/ignition/common/Animation.hh
  graphics/src/Animation.cc
  graphics/src/CMakeLists.txt
Labels: 🏢 edifice

#158 Remove use of _SOURCE and _BINARY dirs in tests
  av/src/AudioDecoder_TEST.cc
  av/src/VideoEncoder_TEST.cc
  events/src/Event_TEST.cc
  events/src/MouseEvent_TEST.cc
  graphics/src/Animation_TEST.cc
  graphics/src/ColladaExporter_TEST.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Dem_TEST.cc
  graphics/src/GTSMeshUtils_TEST.cc
  graphics/src/ImageHeightmap_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/Material_TEST.cc
  graphics/src/MeshManager_TEST.cc
  graphics/src/Mesh_TEST.cc
  graphics/src/OBJLoader.cc
  graphics/src/OBJLoader_TEST.cc
  graphics/src/SVGLoader_TEST.cc
  graphics/src/SubMesh_TEST.cc
  src/Base64_TEST.cc
  src/Battery_TEST.cc
  src/Console_TEST.cc
  src/EnumIface_TEST.cc
  src/MaterialDensity_TEST.cc
  src/Util_TEST.cc
  test/integration/encoder_timing.cc
  test/integration/mesh.cc
  test/integration/video_encoder.cc
  test/test_config.h.in
  test/util.hh
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#123 Add bazel buildsystem support
  BUILD.bazel
  av/BUILD.bazel
  av/src/VideoEncoder.cc
  events/BUILD.bazel
  graphics/BUILD.bazel
  graphics/src/ColladaExporter.cc
  graphics/src/SVGLoader.cc
  profiler/BUILD.bazel
  src/Filesystem_TEST.cc
  src/PluginLoader_TEST.cc
  test/BUILD.bazel
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#185 3 ➡️ 4
  .github/workflows/ci.yml
  Changelog.md
  README.md
  av/src/AudioDecoder_TEST.cc
  av/src/VideoEncoder_TEST.cc
  events/src/Event_TEST.cc
  events/src/MouseEvent_TEST.cc
  graphics/src/Animation_TEST.cc
  graphics/src/ColladaExporter_TEST.cc
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Dem_TEST.cc
  graphics/src/GTSMeshUtils_TEST.cc
  graphics/src/ImageHeightmap_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/Material_TEST.cc
  graphics/src/MeshManager_TEST.cc
  graphics/src/Mesh_TEST.cc
  graphics/src/OBJLoader.cc
  graphics/src/OBJLoader_TEST.cc
  graphics/src/SVGLoader_TEST.cc
  graphics/src/SubMesh_TEST.cc
  src/Base64_TEST.cc
  src/Battery_TEST.cc
  src/Console_TEST.cc
  src/EnumIface_TEST.cc
  src/MaterialDensity_TEST.cc
  src/Util_TEST.cc
  test/data/rectangle.dae
  test/integration/encoder_timing.cc
  test/integration/mesh.cc
  test/integration/video_encoder.cc
  test/test_config.h.in
  test/util.hh
  tutorials/profiler.md
Labels: beta, 🏢 edifice

#163 Add implementation pointer to ign-common classes
  graphics/include/ignition/common/ColladaExporter.hh
  graphics/include/ignition/common/ColladaLoader.hh
  graphics/include/ignition/common/Dem.hh
  graphics/include/ignition/common/Image.hh
  graphics/include/ignition/common/KeyFrame.hh
  graphics/include/ignition/common/Material.hh
  graphics/include/ignition/common/Mesh.hh
  graphics/include/ignition/common/MeshManager.hh
  graphics/include/ignition/common/NodeAnimation.hh
  graphics/include/ignition/common/NodeTransform.hh
  graphics/include/ignition/common/OBJLoader.hh
  graphics/include/ignition/common/Pbr.hh
  graphics/include/ignition/common/STLLoader.hh
  graphics/include/ignition/common/SVGLoader.hh
  graphics/include/ignition/common/Skeleton.hh
  graphics/include/ignition/common/SkeletonAnimation.hh
  graphics/include/ignition/common/SkeletonNode.hh
  graphics/include/ignition/common/SubMesh.hh
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaLoader.cc
  graphics/src/Dem.cc
  graphics/src/Image.cc
  graphics/src/KeyFrame.cc
  graphics/src/Material.cc
  graphics/src/Mesh.cc
  graphics/src/MeshManager.cc
  graphics/src/NodeAnimation.cc
  graphics/src/NodeTransform.cc
  graphics/src/OBJLoader.cc
  graphics/src/Pbr.cc
  graphics/src/STLLoader.cc
  graphics/src/SVGLoader.cc
  graphics/src/Skeleton.cc
  graphics/src/SkeletonAnimation.cc
  graphics/src/SkeletonNode.cc
  graphics/src/SubMesh.cc
Labels: beta, enhancement, 🏢 edifice

#186 Rotate capsule to Z-up
  graphics/include/ignition/common/MeshManager.hh
  graphics/src/MeshManager.cc
  graphics/src/SubMesh_TEST.cc
Labels: beta, bug, 🏢 edifice

#187 Prepare for 4.0.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#188 Fix crash when using BVH animations
  graphics/src/Skeleton.cc
Labels: beta, bug, 🏢 edifice

#189 🎈 4.0.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice

#190 Include windows instructions in examples README.md
  examples/README.md
Labels: Windows, documentation, 🏢 edifice
