Repository gazebosim/gz-common, pull requests merged in 2021-08, with the labels that each got.

#235 🎈 4.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏯 fortress

#240 Fix memory corruption & leaks in Image
  graphics/src/Image.cc
Labels: 🏢 edifice, 🏯 fortress

#241 👩‍🌾 Remove bitbucket-pipelines
  bitbucket-pipelines.yml
Labels: Gazebo 9️

#242 1 ➡️ 3
  bitbucket-pipelines.yml
Labels: 🏰 citadel, 🔮 dome, Gazebo 1️1️
