Repository gazebosim/gz-common, pull requests merged in 2021-02, with the labels that each got.

#118 Added FlagSet utility class
  include/ignition/common/FlagSet.hh
  src/FlagSet_TEST.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#125 Added support for HW-accelerated video encoding.
  av/include/ignition/common/CMakeLists.txt
  av/include/ignition/common/HWEncoder.hh
  av/include/ignition/common/HWVideo.hh
  av/include/ignition/common/Video.hh
  av/include/ignition/common/VideoEncoder.hh
  av/include/ignition/common/ffmpeg_inc.hh
  av/src/CMakeLists.txt
  av/src/HWEncoder.cc
  av/src/Util.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
  av/src/VideoEncoder_TEST.cc
  av/src/ffmpeg_inc.cc
  test/data/test_video.mp4
  test/integration/CMakeLists.txt
  test/integration/video_encoder.cc
  tools/cpplint.py
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#166 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#151 Associate library materials effect with meshes
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  test/data/rectangle.dae
Labels: bug, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#171 Prevent console spam when exporting a mesh with multiple texture coordinates
  graphics/src/ColladaExporter.cc
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#169 Added tutorial on HW-accelerated video encoding.
  tutorials.md.in
  tutorials/hw-encoding.md
  tutorials/profiler.md
Labels: documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#174 Remove issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#175 Fix markdown in tutorial
  tutorials/hw-encoding.md
Labels: documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
