Repository gazebosim/gz-common, pull requests merged in 2021-07, with the labels that each got.

#228 Export lights to dae
  graphics/include/ignition/common/ColladaExporter.hh
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaExporter_TEST.cc
Labels: 🏢 edifice, 🏯 fortress

#230 Add cstring for `std::memcpy`
  graphics/src/Image.cc
Labels: 🏢 edifice, 🏯 fortress

#234 Fix segfault caused by destruction order of Event and Connection
  events/include/ignition/common/Event.hh
  events/src/Event_TEST.cc
Labels: 🏰 citadel, 🔮 dome

#231 Fix a typo in VideoEncoder_TEST.
  av/src/VideoEncoder_TEST.cc
Labels: AV, 🏢 edifice, 🏯 fortress
