Repository gazebosim/gz-common, pull requests merged in 2021-11, with the labels that each got.

#262 Fixed macos symbol in common::profiler
  profiler/src/CMakeLists.txt
Labels: 🏰 citadel, 🔮 dome, macOS, Gazebo 1️1️

#222 Added method to remove meshes from the MeshManager
  graphics/include/ignition/common/MeshManager.hh
  graphics/src/MeshManager.cc
  graphics/src/MeshManager_TEST.cc
Labels: enhancement, 🏢 edifice, 🏯 fortress

#227 Synchronize console writes
  include/ignition/common/Console.hh
  src/Console.cc
  src/Util.cc
  test/performance/logging.cc
Labels: 🏢 edifice, 🏯 fortress

#269 Normalize normal vectors from OBJ.
  graphics/src/OBJLoader.cc
Labels: 🏰 citadel, 🔮 dome, Gazebo 1️1️

#270 ign-common5: drop Bionic
  .github/workflows/ci.yml
Labels: tests, 🌱 garden

#272 Use libexec to install binary remotery_vis
  profiler/src/CMakeLists.txt
Labels: 🏢 edifice, 🏯 fortress, 🌱 garden
