Repository gazebosim/gz-common, pull requests merged in 2021-12, with the labels that each got.

#275 Fix bug in URIPath assignment operator
  src/URI.cc
  src/URI_TEST.cc
Labels: 🏢 edifice, 🏯 fortress, 🌱 garden

#277 3 ➡️ 4
  Changelog.md
  graphics/src/OBJLoader.cc
  profiler/src/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🏢 edifice, 🏯 fortress, 🌱 garden

#266 Support 16 bit heightmaps
  graphics/include/ignition/common/ImageHeightmap.hh
  graphics/src/ImageHeightmap.cc
Labels: help wanted, 🏢 edifice, 🏯 fortress, 🌱 garden

#280 Fixed crash when a Collada file has an empty normal vector
  graphics/src/ColladaLoader.cc
Labels: 🏢 edifice, 🏯 fortress, 🌱 garden

#285 Bumps in garden: use ignition-math7
  .github/ci/packages.apt
  BUILD.bazel
  CMakeLists.txt
  av/BUILD.bazel
  configure.bat
  events/BUILD.bazel
  graphics/BUILD.bazel
  graphics/include/ignition/common/Image.hh
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaLoader.cc
  graphics/src/MeshManager.cc
  graphics/src/NodeTransform.cc
  graphics/src/SVGLoader.cc
  profiler/BUILD.bazel
  src/WorkerPool.cc
Labels: 🌱 garden
