Repository gazebosim/gz-common, pull requests merged in 2022-03, with the labels that each got.

#309 Add some tests for parentPath/basename
  src/Filesystem_TEST.cc
Labels: tests, 🏢 edifice, 🏯 fortress

#308 Fix filesystem::separator behavior
  src/Filesystem.cc
  src/Filesystem_TEST.cc
Labels: 🌱 garden

#292 Geospatial component for heightmaps (2nd try)
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  geospatial/include/ignition/common/CMakeLists.txt
  geospatial/include/ignition/common/geospatial/Dem.hh
  geospatial/include/ignition/common/geospatial/HeightmapData.hh
  geospatial/include/ignition/common/geospatial/ImageHeightmap.hh
  geospatial/src/CMakeLists.txt
  geospatial/src/Dem.cc
  geospatial/src/Dem_TEST.cc
  geospatial/src/ImageHeightmap.cc
  geospatial/src/ImageHeightmap_TEST.cc
  graphics/src/Dem_TEST.cc
  test/data/dem_landscape.tif
  test/data/dem_moon.tif
  test/data/dem_nodata.dem
  test/data/dem_portrait.tif
  test/data/dem_squared.tif
  test/data/dem_unfinished.tif
Labels: 🌱 garden

#324 packages.apt: don't install ruby-ronn
  .github/ci/packages.apt
Labels: 🏢 edifice, 🏯 fortress

#320 4 ➡️ 5 (main)
  .github/ci/packages.apt
  .github/workflows/ci.yml
  include/ignition/common/Filesystem.hh
Labels: 🌱 garden

#323 Class with final destructor should be final
  profiler/src/RemoteryProfilerImpl.hh
Labels: 🌱 garden

#325 Fix compatibility with FFmpeg 5.0
  av/src/AudioDecoder.cc
  av/src/AudioDecoder_TEST.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
Labels: 🏰 citadel

#321 DEM improvements to nodata, buffer and other corner cases
  geospatial/include/ignition/common/geospatial/Dem.hh
  geospatial/src/Dem.cc
  geospatial/src/Dem_TEST.cc
  test/data/dem_nodata_nan.nc
Labels: 🌱 garden, geospatial, MBARI-LRAUV

#333 Fix spelling
  src/URI.cc
Labels: 🏢 edifice, 🏯 fortress

#332 Fix issue 331
  src/Console.cc
  test/integration/console.cc
Labels: 🏰 citadel, Gazebo 1️1️
