Repository gazebosim/gz-common, pull requests merged in 2022-08, with the labels that each got.

#414 ign -> gz : Remove redundant namespace references
  av/src/AudioDecoder.cc
  av/src/HWEncoder.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
  av/src/VideoEncoder_TEST.cc
  events/src/MouseEvent.cc
  events/src/MouseEvent_TEST.cc
  graphics/src/Animation.cc
  graphics/src/BVHLoader.cc
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Dem.cc
  graphics/src/Dem_TEST.cc
  graphics/src/GTSMeshUtils.cc
  graphics/src/GTSMeshUtils_TEST.cc
  graphics/src/Image.cc
  graphics/src/ImageHeightmap.cc
  graphics/src/ImageHeightmap_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/Material.cc
  graphics/src/Mesh.cc
  graphics/src/MeshCSG.cc
  graphics/src/MeshManager_TEST.cc
  graphics/src/OBJLoader.cc
  graphics/src/OBJLoader_TEST.cc
  graphics/src/Pbr.cc
  graphics/src/STLLoader.cc
  graphics/src/SVGLoader.cc
  graphics/src/SVGLoader_TEST.cc
  graphics/src/SubMesh.cc
  graphics/src/SubMesh_TEST.cc
  src/Console.cc
  src/Console_TEST.cc
  src/Filesystem.cc
  src/Filesystem_TEST.cc
  src/MovingWindowFilter_TEST.cc
  src/SystemPaths.cc
  src/SystemPaths_TEST.cc
  src/Time.cc
  src/URI.cc
  src/Util_TEST.cc
  test/integration/encoder_timing.cc
  test/integration/mesh.cc
  test/integration/video_encoder.cc
Labels: 🏰 citadel, ign to gz

#416 Fix deprecation warning from new ffmpeg
  av/src/AudioDecoder.cc
Labels: bug, 🌱 garden

#421 Backport from 5 to 3 - Fix deprecation warning from new ffmpeg
  av/src/AudioDecoder.cc
Labels: 🏰 citadel

#419 🎈 3.14.2
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#422 Merge ign-common3 ➡️ ign-common4
  av/src/AudioDecoder.cc
  av/src/HWEncoder.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
  av/src/VideoEncoder_TEST.cc
  events/src/MouseEvent.cc
  events/src/MouseEvent_TEST.cc
  graphics/src/Animation.cc
  graphics/src/BVHLoader.cc
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Dem.cc
  graphics/src/Dem_TEST.cc
  graphics/src/GTSMeshUtils.cc
  graphics/src/GTSMeshUtils_TEST.cc
  graphics/src/Image.cc
  graphics/src/ImageHeightmap.cc
  graphics/src/ImageHeightmap_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/Material.cc
  graphics/src/Mesh.cc
  graphics/src/MeshCSG.cc
  graphics/src/MeshManager_TEST.cc
  graphics/src/OBJLoader.cc
  graphics/src/OBJLoader_TEST.cc
  graphics/src/Pbr.cc
  graphics/src/STLLoader.cc
  graphics/src/SVGLoader.cc
  graphics/src/SVGLoader_TEST.cc
  graphics/src/SubMesh.cc
  graphics/src/SubMesh_TEST.cc
  src/Console.cc
  src/Console_TEST.cc
  src/Filesystem.cc
  src/Filesystem_TEST.cc
  src/MovingWindowFilter_TEST.cc
  src/SystemPaths.cc
  src/SystemPaths_TEST.cc
  src/Time.cc
  src/URI.cc
  src/Util_TEST.cc
  test/integration/encoder_timing.cc
  test/integration/mesh.cc
  test/integration/video_encoder.cc
Labels: 🏯 fortress

#423 🎈 4.5.2
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#411 Implement XDisplacement function for checking x displacement for all nodes
  graphics/include/gz/common/SkeletonAnimation.hh
  graphics/src/AssimpLoader_TEST.cc
  graphics/src/SkeletonAnimation.cc
  graphics/src/SkeletonAnimation_TEST.cc
  test/data/walk.dae
Labels: bug, 🌱 garden

#427 Fix ABI checker with testing module
  testing/include/gz/common/testing/AutoLogFixture.hh
Labels: bug, 🌱 garden

#409 Add a test for loading gltf with external textures
  graphics/src/AssimpLoader_TEST.cc
  test/data/gltf/PurpleCube.bin
  test/data/gltf/PurpleCube.gltf
  test/data/gltf/PurpleCube_Diffuse.png
Labels: bug, tests, 🌱 garden

#329 Cleanup long-deprecated ifdefs
  CMakeLists.txt
  av/include/gz/common/ffmpeg_inc.hh
  av/src/AudioDecoder.cc
  av/src/Video.cc
  av/src/VideoEncoder.cc
  av/src/ffmpeg_inc.cc
Labels: bug, AV, 🌱 garden, Breaking change
