Repository gazebosim/gz-common, pull requests merged in 2022-06, with the labels that each got.

#359 Fix: Assimp generates normals for all the meshes.
  graphics/src/AssimpLoader.cc
  graphics/src/MeshManager.cc
Labels: 🌱 garden

#365 ign -> gz Environment Variable Migration : gz-common
  Migration.md
  av/include/gz/common/VideoEncoder.hh
  av/src/CMakeLists.txt
  av/src/VideoEncoder.cc
  include/gz/common/SystemPaths.hh
  src/SystemPaths.cc
  src/SystemPaths_TEST.cc
  tutorials/hw-encoding.md
Labels: 🌱 garden, ign to gz

#370 [ign -> gz] CMake functions
  CMakeLists.txt
  av/include/gz/common/CMakeLists.txt
  av/src/CMakeLists.txt
  events/include/gz/common/CMakeLists.txt
  events/src/CMakeLists.txt
  geospatial/include/gz/common/CMakeLists.txt
  geospatial/src/CMakeLists.txt
  graphics/include/gz/common/CMakeLists.txt
  graphics/src/CMakeLists.txt
  include/gz/common/CMakeLists.txt
  profiler/src/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  testing/include/gz/common/CMakeLists.txt
  testing/src/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#371 ign -> gz Macro Migration : gz-common (2)
  profiler/src/CMakeLists.txt
  profiler/src/Profiler_Remotery_TEST.cc
  profiler/src/RemoteryProfilerImpl.cc
Labels: 🌱 garden, ign to gz

#368 Support compressed images and RGBA data in Image class
  graphics/include/gz/common/Image.hh
  graphics/src/Image.cc
  graphics/src/Image_TEST.cc
Labels: 🌱 garden

#373 🎈 4.5.1
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#378 Fix race condition in FileLogger
  include/ignition/common/Console.hh
  src/Console.cc
Labels: 🏯 fortress

#380 4 ➡️ 5
  Changelog.md
  include/gz/common/Console.hh
  src/Console.cc
Labels: 🌱 garden

#352 Rename CMake project to gz
  BUILD.bazel
  CMakeLists.txt
  av/BUILD.bazel
  av/src/CMakeLists.txt
  events/BUILD.bazel
  events/src/CMakeLists.txt
  examples/CMakeLists.txt
  geospatial/src/CMakeLists.txt
  graphics/BUILD.bazel
  graphics/src/CMakeLists.txt
  profiler/BUILD.bazel
  profiler/src/CMakeLists.txt
  src/CMakeLists.txt
  test/BUILD.bazel
  test/integration/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#381 Migrate IGNITION- CMake variables
  CMakeLists.txt
Labels: 🌱 garden

#382 Fix FindSharedLibrary for relative plugin paths
  src/SystemPaths.cc
Labels: 🏰 citadel, Gazebo 1️1️

#383 ign -> gz Partial Docs Migration and Project Name Followups : gz-common
  Changelog.md
  Migration.md
  README.md
  api.md.in
  configure.bat
  examples/README.md
  include/gz/common/SuppressWarning.hh
  profiler/src/CMakeLists.txt
  profiler/src/RemoteryProfilerImpl.cc
  src/PluginUtils_TEST.cc
  src/SignalHandler.cc
  src/SignalHandler_TEST.cc
  src/URI.cc
  test/performance/CMakeLists.txt
  testing/include/gz/common/testing/TestPaths.hh
  tutorials.md.in
  tutorials/hw-encoding.md
  tutorials/install.md
  tutorials/profiler.md
Labels: 🌱 garden
