Repository gazebosim/gz-common, pull requests merged in 2022-10, with the labels that each got.

#447 3.15.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#449 Don't install CMakeLists.txt
  profiler/CMakeLists.txt
  profiler/include/gz/CMakeLists.txt
  profiler/include/gz/common/CMakeLists.txt
Labels: 🏰 citadel

#451 Fixed MeshManager Singleton
  graphics/include/gz/common/MeshManager.hh
  graphics/src/MeshManager.cc
Labels: 🌱 garden

#452 🎈 4.6.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#453 Fix build on case-insensitive filesystems
  profiler/include/CMakeLists.txt
  profiler/include/gz/CMakeLists.txt
  profiler/include/gz/common/CMakeLists.txt
Labels: 🏰 citadel

#454 🎈 3.15.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#455 3 ➡️ 4
  Changelog.md
  profiler/include/CMakeLists.txt
  profiler/include/gz/CMakeLists.txt
  profiler/include/gz/common/CMakeLists.txt
Labels: 🏯 fortress

#456 🎈 4.6.1
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#458 🎈 5.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#461 5.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#462 Fix arm builds
  CMakeLists.txt
  io/src/CSVStreams.cc
Labels: 🌱 garden

#464 5.2.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#465 Increased Image coverage
  graphics/include/gz/common/Image.hh
  graphics/src/Image_TEST.cc
  test/data/gazebo_logo.bmp
  test/data/gazebo_logo.jpeg
Labels: 🏰 citadel

#413 Default name assignment to animations without names
  graphics/src/AssimpLoader.cc
Labels: bug

#467 Improved coverage remotery
  profiler/src/CMakeLists.txt
  profiler/src/Profiler_Error_TEST.cc
Labels: 🏰 citadel

#472 [Backport] Avoid Io.hh header name clash (#471)
  io/include/gz/common/DataFrame.hh
  io/include/gz/common/IOBase.hh
Labels: 🌱 garden

#473 🎈 5.2.2
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden
