Repository gazebosim/gz-common, pull requests merged in 2022-09, with the labels that each got.

#437 Include cstring for memcpy
  graphics/include/ignition/common/Image.hh
Labels: 🏯 fortress

#438 Add gdal to prerequisites
  tutorials/install.md
Labels: 🌱 garden

#439 Fix reading pixel values from single channel 16 bit image
  graphics/src/Image.cc
  graphics/src/Image_TEST.cc
  test/data/grayscale_16bit.png
  test/data/grayscale_8bit.png
Labels: 🌱 garden

#440 Updated install instructions gz-common5
  tutorials/install.md
Labels: 🌱 garden

#441 Improved visualization hw encoding tutorial gz-common5
  tutorials/hw-encoding.md
Labels: 🌱 garden

#443 Update changelogs for common 5.0.0
  Changelog.md
Labels: 🌱 garden

#444 🎈 5.0.0
  CMakeLists.txt
Labels: 🌱 garden

#436 Fix metallic roughness file path for gltf assets
  graphics/src/AssimpLoader.cc
Labels: bug, 🌱 garden

#445 3 ➡️ 4
  Changelog.md
Labels: 🏯 fortress

#442 Suppress a bunch of unnecessary test output
  test/performance/CMakeLists.txt
  test/performance/logging.cc
  testing/include/gz/common/testing/RedirectConsoleStream.hh
  testing/include/gz/common/testing/TestPaths.hh
  testing/src/CMakeLists.txt
  testing/src/RedirectConsoleStream.cc
  testing/src/RedirectConsoleStream_TEST.cc
Labels: 🌱 garden
