Repository gazebosim/gz-common, pull requests merged in 2022-04, with the labels that each got.

#334 3 to 4 20220331
  src/Console.cc
  test/integration/console.cc
Labels: 🏢 edifice, 🏯 fortress

#335 4 to 5 20220401
  src/Console.cc
  src/URI.cc
  test/integration/console.cc
Labels: 🌱 garden

#319 Fix edge case handling for SubMesh::MaterialIndex
  Migration.md
  graphics/include/ignition/common/SubMesh.hh
  graphics/src/ColladaExporter.cc
  graphics/src/ColladaExporter_TEST.cc
  graphics/src/SubMesh.cc
  graphics/src/SubMesh_TEST.cc
Labels: 🌱 garden

#338 Fix typo bug in MaterialIndex
  graphics/src/SubMesh.cc
  graphics/src/SubMesh_TEST.cc
Labels: 🌱 garden

#314 Add common::testing module
  CMakeLists.txt
  av/src/AudioDecoder.cc
  events/src/Event_TEST.cc
  include/ignition/common/TempDirectory.hh
  src/TempDirectory.cc
  src/TempDirectory_TEST.cc
  test/integration/video_encoder.cc
  testing/include/ignition/common/CMakeLists.txt
  testing/include/ignition/common/testing/AutoLogFixture.hh
  testing/include/ignition/common/testing/BazelTestPaths.hh
  testing/include/ignition/common/testing/CMakeTestPaths.hh
  testing/include/ignition/common/testing/TestPaths.hh
  testing/include/ignition/common/testing/Utils.hh
  testing/include/ignition/common/testing/detail/AutoLogFixture.hh
  testing/src/AutoLogFixture_TEST.cc
  testing/src/BazelTestPaths.cc
  testing/src/BazelTestPaths_TEST.cc
  testing/src/CMakeLists.txt
  testing/src/CMakeTestPaths.cc
  testing/src/CMakeTestPaths_TEST.cc
  testing/src/TestPaths.cc
  testing/src/Utils.cc
  testing/src/Utils_TEST.cc
  testing/test_files/example.txt
Labels: tests, 🌱 garden

#339 examples/CMakeLists.txt: fix find version variable
  examples/CMakeLists.txt
Labels: 🌱 garden

#340 Bumps in garden : ign-common5
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden

#341 Use ign-utils instead of ign-cmake utilities
  CMakeLists.txt
  av/src/AudioDecoder_TEST.cc
  av/src/CMakeLists.txt
  src/CMakeLists.txt
  src/Filesystem_TEST.cc
  src/TempDirectory_TEST.cc
  src/WorkerPool_TEST.cc
Labels: 🌱 garden

#342 Bumps in garden : ign-common5
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden

#343 Make Timer_TEST more robust
  src/Timer_TEST.cc
Labels: tests, 🌱 garden

#345 fix switch case fall through warning
  graphics/src/SVGLoader.cc
Labels: 🏯 fortress
