Repository gazebosim/gz-common, pull requests merged in 2022-07, with the labels that each got.

#387 Remove configure.bat, export CXX_STANDARD
  configure.bat
  geospatial/src/Dem.cc
  src/CMakeLists.txt
Labels: 🌱 garden

#389 Support absolute Windows paths with forward slashes in common::FindFile
  src/SystemPaths.cc
  src/SystemPaths_TEST.cc
Labels: 🏯 fortress

#396 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, tests, Gazebo 1️1️, QA

#392 ign -> gz CMake, Python, Partial Source, and File Migrations : gz-common
  .github/ci/packages.apt
  .github/workflows/ci.yml
  .github/workflows/macos.yml
  .github/workflows/pr-collection-labeler.yml
  BUILD.bazel
  CMakeLists.txt
  Changelog.md
  Migration.md
  README.md
  api.md.in
  av/BUILD.bazel
  av/include/CMakeLists.txt
  av/src/VideoEncoder.cc
  events/BUILD.bazel
  events/include/CMakeLists.txt
  geospatial/include/CMakeLists.txt
  graphics/BUILD.bazel
  graphics/include/CMakeLists.txt
  graphics/src/Image.cc
  include/CMakeLists.txt
  include/gz/common/SuppressWarning.hh
  profiler/BUILD.bazel
  profiler/CMakeLists.txt
  profiler/include/gz/common/Profiler.hh
  profiler/src/CMakeLists.txt
  profiler/src/Profiler.cc
  profiler/src/Remotery/gz_remotery_vis.in
  src/CMakeLists.txt
  src/Console.cc
  src/Console_TEST.cc
  src/SystemPaths_TEST.cc
  src/TempDirectory_TEST.cc
  src/Util_TEST.cc
  test/integration/console.cc
  testing/include/CMakeLists.txt
  testing/include/gz/common/testing/BazelTestPaths.hh
  testing/src/BazelTestPaths.cc
  tutorials.md.in
  tutorials/install.md
  tutorials/profiler.md
Labels: 🌱 garden, ign to gz

#397 3 ➡️ 4
  Changelog.md
  README.md
  src/SystemPaths.cc
  test/performance/logging.cc
  tutorials/profiler.md
Labels: 🏯 fortress

#398 Merge ign-common4 ➡️ main
  Changelog.md
  README.md
  src/SystemPaths.cc
  src/SystemPaths_TEST.cc
  test/performance/logging.cc
  tutorials/profiler.md
Labels: 🌱 garden

#395 ign -> gz Provisional Finale: Source Migration : gz-common
  src/Console_TEST.cc
  src/Filesystem_TEST.cc
  src/PluginLoader_TEST.cc
  src/SystemPaths_TEST.cc
  testing/include/gz/common/testing/TestPaths.hh
  testing/include/gz/common/testing/detail/AutoLogFixture.hh
  testing/src/TestPaths.cc
Labels: 🌱 garden, ign to gz

#400 Remove deprecated include
  src/CMakeLists.txt
Labels: 🌱 garden

#377 Support lunar coordinate transformations
  geospatial/include/gz/common/geospatial/Dem.hh
  geospatial/src/Dem.cc
  geospatial/src/Dem_TEST.cc
Labels: 🌱 garden

#399 Change IGN_DESIGNATION to GZ_DESIGNATION
  api.md.in
  tutorials.md.in
Labels: 🏰 citadel, Gazebo 1️1️, ign to gz, needs upstream release

#372 Add API for getting Image bytes as std::vector
  Migration.md
  geospatial/src/ImageHeightmap.cc
  graphics/include/gz/common/Image.hh
  graphics/src/Image.cc
  graphics/src/Image_TEST.cc
Labels: enhancement, 🌱 garden

#394 Add code coverage ignore file
  CMakeLists.txt
  coverage.ignore.in
Labels: 🏰 citadel, Gazebo 1️1️, QA

#405 Merge ign-common3 ➡️ ign-common4
  CMakeLists.txt
  api.md.in
  coverage.ignore.in
  tutorials.md.in
Labels: 🏯 fortress

#406 Merge ign-common4 ➡️ main
  coverage.ignore.in
Labels: 🌱 garden

#403 Introduces GZ_MESH_FORCE_ASSIMP flag
  graphics/include/gz/common/MeshManager.hh
  graphics/src/MeshManager.cc
Labels: 🌱 garden

#393 Use assimp for loading meshes
  .github/ci/packages.apt
  CMakeLists.txt
  graphics/include/gz/common/AssimpLoader.hh
  graphics/include/gz/common/Material.hh
  graphics/include/gz/common/MeshManager.hh
  graphics/include/gz/common/Pbr.hh
  graphics/src/AssimpLoader.cc
  graphics/src/AssimpLoader_TEST.cc
  graphics/src/CMakeLists.txt
  graphics/src/Material.cc
  graphics/src/Material_TEST.cc
  graphics/src/MeshManager.cc
  graphics/src/Pbr.cc
  graphics/src/Pbr_TEST.cc
  test/data/box.fbx
  test/data/box.glb
  test/data/fully_featured.glb
  test/integration/mesh.cc
Labels: enhancement, 🌱 garden, Breaking change
