Repository gazebosim/gz-common, pull requests merged in 2022-01, with the labels that each got.

#287 Backport of #240 to fix memory leaks in Image.
  graphics/src/Image.cc
Labels: 🏰 citadel, Gazebo 1️1️

#284 Upload coverage for Focal builds
  .github/workflows/ci.yml
Labels: tests, 🌱 garden

#288 🎈 4.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏯 fortress

#267 Geospatial component for heightmap & DEMs
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  geospatial/include/ignition/common/CMakeLists.txt
  geospatial/include/ignition/common/Dem.hh
  geospatial/include/ignition/common/HeightmapData.hh
  geospatial/include/ignition/common/ImageHeightmap.hh
  geospatial/src/CMakeLists.txt
  geospatial/src/Dem.cc
  geospatial/src/Dem_TEST.cc
  geospatial/src/ImageHeightmap.cc
  geospatial/src/ImageHeightmap_TEST.cc
  test/data/dem_landscape.tif
  test/data/dem_nodata.dem
  test/data/dem_portrait.tif
  test/data/dem_squared.tif
  test/data/dem_unfinished.tif
Labels: 🌱 garden

#289 Move geospatial headers to subfolder
  Migration.md
  geospatial/include/ignition/common/geospatial/Dem.hh
  geospatial/include/ignition/common/geospatial/HeightmapData.hh
  geospatial/include/ignition/common/geospatial/ImageHeightmap.hh
  geospatial/src/Dem.cc
  geospatial/src/Dem_TEST.cc
  geospatial/src/ImageHeightmap.cc
  geospatial/src/ImageHeightmap_TEST.cc
Labels: 🌱 garden

#291 Revert geospatial component for now
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  geospatial/include/ignition/common/CMakeLists.txt
  geospatial/src/CMakeLists.txt
  graphics/include/ignition/common/Dem.hh
  graphics/include/ignition/common/HeightmapData.hh
  graphics/include/ignition/common/ImageHeightmap.hh
  graphics/src/Dem.cc
  graphics/src/Dem_TEST.cc
  graphics/src/ImageHeightmap.cc
  graphics/src/ImageHeightmap_TEST.cc
  test/data/dem_landscape.tif
  test/data/dem_nodata.dem
  test/data/dem_portrait.tif
  test/data/dem_squared.tif
  test/data/dem_unfinished.tif
Labels: 🌱 garden

#290 README: update badge
  README.md
Labels: 🌱 garden

#294 Move performance test to examples
  examples/CMakeLists.txt
  examples/logging_performance.cc
Labels: 🏢 edifice, 🏯 fortress

#295 Use SuppressWarning from ign-utils
  av/include/ignition/common/AudioDecoder.hh
  av/include/ignition/common/HWEncoder.hh
  av/include/ignition/common/Video.hh
  av/include/ignition/common/VideoEncoder.hh
  events/include/ignition/common/KeyEvent.hh
  events/include/ignition/common/MouseEvent.hh
  graphics/include/ignition/common/SubMesh.hh
  include/ignition/common/Console.hh
  include/ignition/common/Plugin.hh
  include/ignition/common/PluginLoader.hh
  include/ignition/common/SuppressWarning.hh
  include/ignition/common/Timer.hh
  include/ignition/common/detail/PluginMacros.hh
  include/ignition/common/detail/SuppressWarning.hh
  src/CMakeLists.txt
  test/plugins/CMakeLists.txt
  test/static_assertions/CMakeLists.txt
Labels: 🌱 garden
