Repository gazebosim/gz-common, pull requests merged in 2022-02, with the labels that each got.

#304 Fix out-of-bound access in URI
  src/URI.cc
Labels: 🏢 edifice, 🏯 fortress

#303 Fix out-of-bounds access in sanitizeSlashes
  src/Filesystem.cc
Labels: 🏰 citadel, Gazebo 1️1️

#305 3 ➡️ 4
  src/Filesystem.cc
Labels: 🏢 edifice, 🏯 fortress

#302 Merge 4 -> main
  Changelog.md
  examples/CMakeLists.txt
  examples/logging_performance.cc
  src/Filesystem.cc
  src/URI.cc
Labels: 🌱 garden

#238 Update to use std::filesystem rather than Boost
  examples/logging_performance.cc
  include/ignition/common/Filesystem.hh
  include/ignition/common/SystemPaths.hh
  src/CMakeLists.txt
  src/DirIter.cc
  src/Filesystem.cc
  src/FilesystemBoost.cc
  src/SystemPaths.cc
  src/TempDirectory.cc
  src/Util.cc
Labels: 🌱 garden

#299 Utilize ImplPtr for Timer
  include/ignition/common/Timer.hh
  src/Timer.cc
  src/Timer_TEST.cc
Labels: 🌱 garden

#282 Update tests to use more STL functionality
  src/Filesystem_TEST.cc
Labels: tests, 🌱 garden

#310 Image: make several methods const
  Migration.md
  graphics/include/ignition/common/Image.hh
  graphics/src/Image.cc
Labels: 🌱 garden

#312 Adds an `isRelativePath` to determine if path is relative
  include/ignition/common/Filesystem.hh
  src/Filesystem.cc
  src/Filesystem_TEST.cc
Labels: 🌱 garden

#316 [ign-common4] Add CI support for Jammy
  .github/workflows/ci.yml
Labels: 🏢 edifice, 🏯 fortress
