Repository gazebosim/gz-common, pull requests merged in 2023-04, with the labels that each got.

#501 [Backport] Include cstring for memcpy
  graphics/include/gz/common/Image.hh
Labels: 🏰 citadel

#504 Backport #497 to ign-common3: Fix for ffmpeg v6
  av/src/AudioDecoder.cc
  av/src/Video.cc
Labels: 🏰 citadel

#506 Merge ign-common3 ➡️ ign-common4
  av/src/AudioDecoder.cc
  av/src/Video.cc
Labels: 🏯 fortress

#507 Merge ign-common4 ➡️ gz-common5
  av/src/Video.cc
Labels: 🌱 garden, 🎵 harmonic

#498 Add support for bayer images to be saved in a directory
  graphics/src/Image.cc
Labels: 🌱 garden, 🎵 harmonic

#508 Prepare for 5.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic
