Repository gazebosim/gz-common, pull requests merged in 2023-03, with the labels that each got.

#490 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#491 Merge ign-common3 ➡️ ign-common4
  .github/workflows/ci.yml
  graphics/include/gz/common/Image.hh
  graphics/src/BVHLoader_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/STLLoader_TEST.cc
  profiler/src/CMakeLists.txt
  profiler/src/Profiler_Error_TEST.cc
  test/data/cmu-13_26.bvh
  test/data/cube.stl
  test/data/cube_binary.stl
  test/data/gazebo_logo.bmp
  test/data/gazebo_logo.jpeg
Labels: 🏯 fortress

#493 Add marcoag as codeowner
  .github/CODEOWNERS
Labels: 🏰 citadel

#492 Merge ign-common4 ➡️ gz-common5
  .github/workflows/ci.yml
  Changelog.md
  graphics/include/gz/common/Image.hh
  graphics/src/BVHLoader_TEST.cc
  graphics/src/Image_TEST.cc
  graphics/src/STLLoader_TEST.cc
  profiler/src/CMakeLists.txt
  profiler/src/Profiler_Error_TEST.cc
  test/data/cmu-13_26.bvh
  test/data/cube.stl
  test/data/cube_binary.stl
  test/data/gazebo_logo.bmp
  test/data/gazebo_logo.jpeg
Labels: 🌱 garden, 🎵 harmonic

#494 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#495 Merge ign-common3 ➡️ ign-common4
  .github/CODEOWNERS
  COPYING
  LICENSE
Labels: 🏯 fortress

#496 Merge ign-common4 ➡️ gz-common5
  .github/CODEOWNERS
  COPYING
  LICENSE
Labels: 🌱 garden, 🎵 harmonic

#497 Fix for ffmpeg v6
  av/src/AudioDecoder.cc
  av/src/Video.cc
Labels: 🌱 garden, 🎵 harmonic

#499 Cherry-pick #451: Fixed MeshManager Singleton
  graphics/include/gz/common/MeshManager.hh
  graphics/src/MeshManager.cc
Labels: 🏰 citadel

#500 Merge ign-common3 ➡️ ign-common4
  graphics/include/gz/common/MeshManager.hh
  graphics/src/MeshManager.cc
Labels: 🏯 fortress
