Repository gazebosim/gz-common, pull requests merged in 2023-05, with the labels that each got.

#510 🎈 4.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#513 Fix missing cstdint header in latest gcc build
  profiler/src/RemoteryProfilerImpl.hh
Labels: 🏰 citadel

#511 Port: 4 to 5
  Changelog.md
  av/src/VideoEncoder.cc
  events/src/Event.cc
  examples/CMakeLists.txt
  examples/logging_performance.cc
  examples/util.cc
  geospatial/src/Dem.cc
  geospatial/src/ImageHeightmap.cc
  graphics/include/gz/common/ColladaLoader.hh
  graphics/include/gz/common/GTSMeshUtils.hh
  graphics/include/gz/common/Image.hh
  graphics/include/gz/common/Material.hh
  graphics/include/gz/common/MeshExporter.hh
  graphics/include/gz/common/STLLoader.hh
  graphics/src/Image.cc
  graphics/src/MeshManager.cc
  include/gz/common/Base64.hh
  include/gz/common/Console.hh
  include/gz/common/EnumIface.hh
  include/gz/common/TemplateHelpers.hh
  include/ignition/common/SpecializedPlugin.hh
  io/include/gz/common/DataFrame.hh
  profiler/include/gz/common/Profiler.hh
  src/Console.cc
  src/Plugin.cc
  src/SignalHandler.cc
  src/URI.cc
  src/WorkerPool_TEST.cc
  testing/include/gz/common/testing/AutoLogFixture.hh
  testing/include/gz/common/testing/RedirectConsoleStream.hh
  testing/include/gz/common/testing/detail/AutoLogFixture.hh
  testing/src/RedirectConsoleStream.cc
  testing/src/RedirectConsoleStream_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#515 Header was dropped in the forward port and breaks downstream
  include/gz/common/Console.hh
Labels: 🌱 garden, 🎵 harmonic

#517 Include cstdint to build with GCC 13
  profiler/src/ProfilerImpl.hh
Labels: 🏰 citadel
