Repository gazebosim/gz-common, pull requests merged in 2023-12, with the labels that each got.

#561 Fix error output when creating directories
  src/Filesystem.cc
Labels: 🏰 citadel

#565 Backwards compatible assimp texture name fix
  graphics/src/AssimpLoader.cc
  graphics/src/AssimpLoader_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#559 Merge ign-common3 ➡️ ign-common4
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  include/gz/common/Filesystem.hh
  profiler/src/ProfilerImpl.hh
  profiler/src/RemoteryProfilerImpl.hh
  src/Console.cc
  src/EnumIface_TEST.cc
  src/Filesystem.cc
Labels: 🏯 fortress

#566 Update CI badges in README
  README.md
Labels: 🌱 garden, 🎵 harmonic
