Repository gazebosim/gz-common, pull requests merged in 2024-05, with the labels that each got.

#603 Fix deprecation warnings
  av/src/AudioDecoder.cc
  av/src/Video.cc
  include/gz/common/EnumIface.hh
Labels: 🏰 citadel

#604 Merge ign-common3 ➡️ ign-common4
  av/src/AudioDecoder.cc
  av/src/Video.cc
  include/gz/common/EnumIface.hh
Labels: 🏯 fortress

#605 Merge ign-common4 ➡️ gz-common5
  av/src/AudioDecoder.cc
  av/src/Video.cc
Labels: 🌱 garden, 🎵 harmonic

#587 Add package.xml
  .github/workflows/package_xml.yml
  package.xml
Labels: 🌱 garden, 🎵 harmonic

#606 Generate a more unique texture name for glb embedded textures
  graphics/src/AssimpLoader.cc
  graphics/src/AssimpLoader_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#610 Merge gz-common5 ➡️ main
  .github/workflows/macos.yml
  .github/workflows/package_xml.yml
  Changelog.md
  av/src/AudioDecoder.cc
  av/src/Video.cc
  geospatial/include/gz/common/geospatial/Dem.hh
  geospatial/include/gz/common/geospatial/HeightmapData.hh
  graphics/src/AssimpLoader.cc
  graphics/src/AssimpLoader_TEST.cc
  package.xml
Labels: 🏛️ ionic
