Repository gazebosim/gz-common, pull requests merged in 2024-12, with the labels that each got.

#652 Remove Conda Windows warnings
  graphics/src/AssimpLoader.cc
  graphics/src/AssimpLoader_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#658 Prepare for 6.0.1 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic, 🪵 jetty

#655 Add include <chrono> for system_clock
  events/include/gz/common/Event.hh
Labels: 🎵 harmonic
