Repository gazebosim/gz-common, pull requests merged in 2024-08, with the labels that each got.

#621 Merge 5 -> main
  graphics/include/gz/common/SubMesh.hh
  graphics/src/SubMesh.cc
  graphics/src/SubMesh_TEST.cc
  graphics/src/VHACD/VHACD.h
Labels: 🏛️ ionic

#620 Fix crash when calling absPath with empty input
  src/Filesystem.cc
  src/Filesystem_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#622 Remove debug logging introduced accidentally in PR review
  graphics/src/AssimpLoader.cc
Labels: 🌱 garden, 🎵 harmonic

#617 Replace GTS with CDT
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  codecov.yml
  coverage.ignore.in
  graphics/include/gz/common/DelaunayTriangulation.hh
  graphics/include/gz/common/GTSMeshUtils.hh
  graphics/include/gz/common/MeshCSG.hh
  graphics/include/gz/common/MeshManager.hh
  graphics/src/CDT/CDT.h
  graphics/src/CDT/CDT.hpp
  graphics/src/CDT/CDTUtils.h
  graphics/src/CDT/CDTUtils.hpp
  graphics/src/CDT/KDTree.h
  graphics/src/CDT/LICENSE
  graphics/src/CDT/LocatorKDTree.h
  graphics/src/CDT/README.md
  graphics/src/CDT/Triangulation.h
  graphics/src/CDT/Triangulation.hpp
  graphics/src/CDT/portable_nth_element.hpp
  graphics/src/CDT/predicates.h
  graphics/src/CDT/remove_at.hpp
  graphics/src/CMakeLists.txt
  graphics/src/DelaunayTriangulation.cc
  graphics/src/DelaunayTriangulation_TEST.cc
  graphics/src/GTSMeshUtils.cc
  graphics/src/MeshCSG.cc
  graphics/src/MeshManager.cc
  package.xml
Labels: beta, 🏛️ ionic

#618 Use self-pipe trick to implement signal handlers
  src/SignalHandler.cc
  src/SignalHandler_TEST.cc
Labels: beta, Breaking change, 🏛️ ionic

#626 Update Changelog, README and prepare for gz-common6.0.0~pre1 release
  CMakeLists.txt
  Changelog.md
  README.md
Labels: 🏛️ ionic

#615 Experimenting with spdlog
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  examples/console.cc
  include/gz/common/Console.hh
  package.xml
  src/CMakeLists.txt
  src/Console.cc
  src/Console_TEST.cc
  testing/src/AutoLogFixture_TEST.cc
Labels: beta, Breaking change, 🏛️ ionic

#629 Prepare for gz-common6.0.0~pre2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic
