Repository gazebosim/gz-common, pull requests merged in 2024-01, with the labels that each got.

#567 🎈 3.17.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#568 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#570 Merge ign-common3 ➡️ ign-common4
  Changelog.md
Labels: 🏯 fortress

#572 Merge ign-common4 ➡️ gz-common5
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  profiler/src/ProfilerImpl.hh
  src/EnumIface_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#574 Clarify GDAL version requirement
  CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic

#571 Multiple memory cleanup fixes
  graphics/src/AssimpLoader_TEST.cc
  graphics/src/ColladaExporter_TEST.cc
  graphics/src/ColladaLoader.cc
  graphics/src/ColladaLoader_TEST.cc
  graphics/src/Image.cc
  graphics/src/OBJLoader_TEST.cc
  graphics/src/STLLoader_TEST.cc
  graphics/src/Skeleton.cc
  graphics/src/SkeletonAnimation_TEST.cc
  graphics/src/SkeletonNode.cc
Labels: 🌱 garden, 🎵 harmonic

#573 Be louder when graphics is missing for geospatial
  CMakeLists.txt
  geospatial/src/CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic
